# Generated by Django 4.0.3 on 2022-03-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='prof',
            field=models.ManyToManyField(to='rate.profs'),
        ),
    ]
