# Generated by Django 4.0.3 on 2022-03-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_modules_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='profs',
            name='name_code',
            field=models.CharField(default='', max_length=5, verbose_name="Proffessor's abbreviated name"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modules',
            name='semester',
            field=models.IntegerField(verbose_name='Semester this module is being taught'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='year',
            field=models.IntegerField(verbose_name='Year module is taught'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.SmallIntegerField(verbose_name='Proffessor rating'),
        ),
    ]
