# Generated by Django 4.0.3 on 2022-03-22 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0005_remove_ratings_profs_ratings_profs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='profs',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rate.profs'),
        ),
    ]
