# Generated by Django 4.0.3 on 2022-03-22 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0007_remove_ratings_profs_ratings_profs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profs',
            unique_together=set(),
        ),
    ]
